#Iris Classification

## Import the relevant libraries

In [2]:
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import os

## Data Preprocessing

### 1) Load the data

In [12]:
iris_data = pd.read_csv('/content/iris.csv')
iris_data.head()
np_iris = iris_data.to_numpy()

In [ ]:
iris_data.describe()

In [ ]:
iris_data.info()

In [ ]:
iris_data['Species'].unique()

### Label encoding the categorical data

In [22]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
iris_data['Species'] = label_encoder.fit_transform(
                                iris_data['Species'])
iris_data

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

### One hot encoding targets

In [31]:
y_data = tf.keras.utils.to_categorical(y_data,3)
y_data

array([[[0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       [[0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       [[0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]],

       ...,

       [[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.]]], dtype=float32)

### Split into features and targets

In [23]:
x_data = iris_data.iloc[: , :-1]
y_data = iris_data.iloc[: , -1]
y_data

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

## Splitting into train and test set

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split( x_data, y_data, test_size=0.10)

## Feature Scaling

In [26]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [27]:
x_train

array([[ 0.83705448, -0.11913348,  0.83985478,  1.05830894],
       [-0.13605514,  3.00812029, -1.26188601, -1.03696815],
       [ 1.32360929,  0.10424179,  0.66944336,  0.40353485],
       [ 1.9318028 , -0.56588402,  1.35108902,  0.92735412],
       [ 0.22886097, -1.90613563,  0.15820912, -0.25123924],
       [ 0.47213837, -0.34250875,  0.32862053,  0.14162521],
       [ 2.2967189 , -0.11913348,  1.35108902,  1.45117339],
       [ 0.22886097, -0.11913348,  0.61263956,  0.7963993 ],
       [-0.37933255, -1.45938509,  0.04460151, -0.12028443],
       [ 1.08033188,  0.55099233,  1.1238738 ,  1.71308302],
       [ 1.08033188,  0.10424179,  0.55583575,  0.40353485],
       [-0.98752606, -2.35288617, -0.12580991, -0.25123924],
       [ 1.44524799,  0.32761706,  0.55583575,  0.27258003],
       [ 1.68852539,  0.32761706,  1.29428522,  0.7963993 ],
       [-1.71735827, -0.11913348, -1.37549362, -1.29887779],
       [-1.10916476,  0.10424179, -1.26188601, -1.29887779],
       [-1.10916476, -1.

In [28]:
x_test

array([[6.4, 3.2, 4.5, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [6.1, 2.8, 4.7, 1.2],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.4, 1.7, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.5, 1.4, 0.3],
       [6. , 2.9, 4.5, 1.5],
       [6.6, 3. , 4.4, 1.4],
       [5.9, 3.2, 4.8, 1.8],
       [6.3, 2.7, 4.9, 1.8],
       [6.4, 2.9, 4.3, 1.3]])

In [33]:
print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

(135, 4) (135,) (15, 4) (15,)
